make iter script a bit easier to use

diff --git a/2016-align/iter b/2016-align/iter
--- a/2016-align/iter
+++ b/2016-align/iter
@@ -9,23 +9,28 @@ help() {
     Portability has not been investigated.
 
  USAGE:
-  ./iter <cmd> [args...]
+  ./iter <cmd> [<stage>] [args...]
+
+ STAGES:
+  trk  : tracking and accumulation with hps-java
+  pede : minimization of parameters with pede
 
  COMMANDS:
-  help           : print this help and exit
-  init DETNAME   : create a new workspace for DETNAME detector
-  submit DETNAME : submit tracking jobs already initialized for DETNAME detector
-  watch [SLEEP]  : watch users slurm queue, reporting totals every SLEEP seconds (default 360s = 5min)
-  hadd DETNAME   : merge gblplots from output of tracking using DETNAME
-  pede-init DETNAME : init a pede subdirectory for DETNAME detector
-  pede-run DETNAME  : run pede for DETNAME detector and apply results
+  help                 : print this help and exit
+  hadd DETNAME         : merge gblplots from output of tracking using DETNAME
+  init STAGE DETNAME   : create a new workspace for DETNAME detector and STAGE
+  submit STAGE DETNAME : submit jobs already initialized for DETNAME detector and STAGE
+  trk DETNAME          : do both init and submit commands for the tracking stage
+  pede DETNAME         : do both init and submit commands for the pede stage
+  full DETNAME         : do a full iteration (both iterations) for DETNAME
+                         parameters to float are chosen before plots are ready
 
 HELP
 }
 
 # initialize a new detector workspace
 #  1 - detector name
-init() {
+trk-init() {
   local detname="${1%/}"
   if [ -d "$1" ]; then
     echo "ERROR: '${detname}' already exists."
@@ -42,7 +47,7 @@ init() {
   hps-mc-job-template \
     -j 1 \
     -a ${detname}/tracking-vars.json \
-    -i events tracking/physrun-2016-part-007800-HPS-PhysicsRun2016-Pass2.list 1 \
+    -i events tracking/physrun-2016-run-007800-HPS-PhysicsRun2016-Pass2-fee-skim.list 1 \
     tracking/job.json.templ \
     ${detname}/tracking-jobs.json
   return $?
@@ -50,20 +55,21 @@ init() {
 
 # submit tracking jobs to slurm
 #  1 - detector name
-submit() {
+trk-submit() {
   local detname="${1%/}"
   if [ ! -d "$detname" ]; then
     echo "ERROR: '${detname}' un-initialized."
     return 1
   fi
 
+  mkdir -p ${detname}/{sh,log,scratch} || return 1
   
   hps-mc-batch slurm \
     --queue shared \
     --env $(which hps-mc-env.sh) \
-    -S ${detname}/sh \
-    -l ${detname}/log \
-    -d ${detname}/scratch \
+    -S $(realpath ${detname}/sh) \
+    -l $(realpath ${detname}/log) \
+    -d $(realpath ${detname}/scratch) \
     --memory 3500 \
     -c tracking/batch.cfg \
     track_align \
@@ -73,7 +79,7 @@ submit() {
 }
 
 # watch user's slurm queue and report summary counts to terminal
-watch() {
+__watch() {
   local squeue_poll_file="${TMPDIR:-/scratch/${USER}}/squeue-poll-$$.list"
   local sleep_time=${1:-360} 
   while true; do
@@ -105,7 +111,7 @@ pede-init() {
 
 # run pede for input DETNAME
 #  1 - DETNAME
-pede-run() {
+pede-submit() {
   local detname="${1%/}"
   if [ ! -d "${detname}" ]; then
     echo "ERROR: '${detname}' uninitializaed."
@@ -139,8 +145,74 @@ hadd() {
   return $?
 }
 
+__num_user_jobs() {
+  squeue -u $USER | grep -c $USER
+}
+
+# wait until $USER has no jobs in squeue
+swait() {
+  # pause to allow squeue to catch up
+  sleep 2
+  num=$(__num_user_jobs)
+  while (( num > 0 )); do
+    sleep 20
+    num=$(__num_user_jobs)
+  done
+}
+
+# do both stages of an iteration for DETNAME
+#  1 - DETNAME
+full() {
+  local detname="${1%/}"
+  # initialize detector for tracking
+  trk-init ${detname} || return $?
+  # have user define parameters to float now so they
+  # can walk away during tracking+minimization
+  mkdir ${detname}/pede || return $?
+  sed "s|DETNAME|${detname}|g" pede/job.json > ${detname}/pede/job.json || return $?
+  vim ${detname}/pede/job.json
+  # continue after user closes vim
+  trk-submit ${detname} || return $?
+  swait
+  find $PWD/${detname}/tracking/ -type f -name "*.bin" > ${detname}/pede/mille-bin.list || return $?
+  pede-submit ${detname} || return $?
+  swait
+  tail -50 ${detname}/pede/run.out
+}
+
 case $1 in
-  init|help|submit|watch|pede-init|pede-run|hadd)
+  init|submit)
+    if [ $# -lt 3 ]; then
+      echo "ERROR: command '$1' requires a two arguments STAGE DETNAME"
+      exit 1
+    fi
+    stage=$2
+    detname=$3
+    case $2 in
+      trk|pede)
+        ${2}-${1} ${@:3} || return $?
+        if [ "$1" = "submit" ]; then
+          watch squeue -u $USER
+        fi
+        return $?
+        ;;
+      *)
+        echo "ERROR: '$2' not a valid stage: 'trk' or 'pede'"
+        exit 1
+        ;;
+    esac
+    ;;
+  trk|pede)
+    if [ $# -lt 2 ]; then
+      echo "ERROR: command '$1' requires a detector after it"
+      exit 1
+    fi
+    $1-init ${@:2} || return $?
+    $2-submit ${@:2} || return $?
+    watch squeue -u $USER
+    return $?
+    ;;
+  help|hadd|full)
     ${1} ${@:2}
     exit $?
     ;;
