start using pede/job.json as template for future pede jobs

diff --git a/2016-align/iter b/2016-align/iter
--- a/2016-align/iter
+++ b/2016-align/iter
@@ -4,7 +4,9 @@
 help() {
   cat <<\HELP
 
-  Run various alignment subtasks
+  Run various alignment subtasks that make up iterations.
+  WARNING: This script is meant to be used at SDF within hps/2016-align.
+    Portability has not been investigated.
 
  USAGE:
   ./iter <cmd> [args...]
@@ -14,6 +16,7 @@ help() {
   init DETNAME   : create a new workspace for DETNAME detector
   submit DETNAME : submit tracking jobs already initialized for DETNAME detector
   watch SLEEP    : watch users slurm queue, reporting totals every SLEEP seconds
+  pede-init DETNAME : init a pede subdirectory for DETNAME detector
 
 HELP
 }
@@ -21,7 +24,7 @@ HELP
 # initialize a new detector workspace
 #  1 - detector name
 init() {
-  local detname="$1"
+  local detname="${1%/}"
   if [ -d "$1" ]; then
     echo "ERROR: '${detname}' already exists."
     return 1
@@ -46,7 +49,7 @@ init() {
 # submit tracking jobs to slurm
 #  1 - detector name
 submit() {
-  local detname="$1"
+  local detname="${1%/}"
   if [ ! -d "$detname" ]; then
     echo "ERROR: '${detname}' un-initialized."
     return 1
@@ -79,8 +82,26 @@ watch() {
   done
 }
 
+# initialize pede for input DETNAME
+pede-init() {
+  local detname="${1%/}"
+  if [ ! -d "${detname}" ]; then
+    echo "ERROR: '${detname}' uninitializaed."
+    return 1
+  fi
+
+  if ! mkdir ${detname}/pede; then
+    echo "ERROR: '${detname}' already pede-initialized. rm ${detname}/pede if you wish to re-init."
+    return 2
+  fi
+
+  find $PWD/${detname}/tracking/ -type f -name "*.bin" > ${detname}/pede/mille-bin.list
+  sed "s|DETNAME|${detname}|g" pede/job.json > ${detname}/pede/job.json
+  vim ${detname}/pede/job.json
+}
+
 case $1 in
-  init|help|submit|watch)
+  init|help|submit|watch|pede-init)
     ${1} ${@:2}
     exit $?
     ;;
